FROM amazonlinux:2023

# Install required dependencies
RUN dnf install -y \
    python3 python3-pip \
    nodejs npm \
    aws-cli \
    jq \
    && dnf clean all

# Install AWS CDK
RUN npm install -g aws-cdk && pip3 install boto3

# Set working directory
WORKDIR /app

# Default command
CMD ["bash"]
