IMAGE_NAME=cdk-python
DOCKERHUB_USERNAME?=$(shell echo $$DOCKERHUB_USERNAME)

build:
	@echo "Building Docker image: $(IMAGE_NAME)"
	docker build -t $(IMAGE_NAME) .

push:
	@echo "Tagging image"
	docker tag $(IMAGE_NAME):latest $(DOCKERHUB_USERNAME)/cdk-python:latest
	@echo "Pushing image to Docker Hub"
	docker push $(IMAGE_NAME):latest

clean:
	@echo "Removing local Docker images"
	docker rmi -f $(IMAGE_NAME) || true

.PHONY: build push clean
